[workspace]
resolver = "2"
members = ["registry_core", "registry_program", "methods", "methods/guest", "cli", "e2e_tests", "lez-registry-ffi"]

[workspace.dependencies]
risc0-zkvm = { version = "=3.0.5", features = ['std'] }
risc0-build = "=3.0.5"
nssa_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3", features = ["host"] }
nssa = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3" }
common = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3" }
wallet = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3" }
sequencer_service_rpc = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0-rc3" }
lez-framework = { git = "https://github.com/logos-co/spel", rev = "eed4ad7" }
lez-cli = { git = "https://github.com/logos-co/spel", rev = "eed4ad7" }
borsh = "1.5.7"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.50", features = ["net", "rt-multi-thread", "sync", "macros", "full"] }
