[package]
name = "lez-registry-e2e"
version = "0.1.0"
edition = "2024"

[[test]]
name = "e2e_registry"
path = "tests/e2e_registry.rs"

[dependencies]
registry_core = { path = "../registry_core" }
nssa = { workspace = true }
nssa_core = { workspace = true }
common = { workspace = true }
risc0-zkvm = { workspace = true }
borsh = { workspace = true }
tokio = { workspace = true }

[lib]
path = "src/lib.rs"
